import React from 'react';

export const TICKER_ITEMS: Record<string, string[]> = {
  RU: ["UI/UX Дизайн", "Разработка сайтов", "SEO продвижение", "Настройка рекламы", "Создание ботов", "Копирайтинг", "Перевод текстов", "Монтаж видео", "Оформление соцсетей", "Аналитика данных", "Разработка iOS/Android", "3D Моделирование"],
  EN: ["UI/UX Design", "Web Development", "SEO Optimization", "Ad Setup", "Bot Creation", "Copywriting", "Text Translation", "Video Editing", "SMM & Social Media", "Data Analytics", "iOS/Android Dev", "3D Modeling"],
  PL: ["UI/UX Design", "Tworzenie stron", "Pozycjonowanie SEO", "Konfiguracja reklam", "Tworzenie botów", "Copywriting", "Tłumaczenia", "Montaż wideo", "Media społecznościowe", "Analityka danych", "Aplikacje mobilne", "Modelowanie 3D"],
  DE: ["UI/UX Design", "Webentwicklung", "SEO Optimierung", "Werbung", "Bot-Erstellung", "Texterstellung", "Übersetzung", "Videobearbeitung", "Social Media", "Datenanalyse", "App-Entwicklung", "3D-Modellierung"],
  ES: ["Diseño UI/UX", "Desarrollo Web", "SEO", "Publicidad", "Creación de Bots", "Redacción", "Traducción", "Edición de Video", "Redes Sociales", "Análisis de Datos", "Desarrollo de Apps", "Modelado 3D"],
  IT: ["Design UI/UX", "Sviluppo Web", "Ottimizzazione SEO", "Pubblicità", "Creazione Bot", "Copywriting", "Traduzione", "Montaggio Video", "Social Media", "Analisi dei Dati", "Sviluppo App", "Modellazione 3D"],
  FR: ["Design UI/UX", "Développement Web", "SEO", "Publicité", "Création de Bots", "Rédaction", "Traduction", "Montage Vidéo", "Réseaux Sociaux", "Analyse de Données", "Développement d'Applis", "Modélisation 3D"]
};

export const t: Record<string, any> = {
  RU: {
    global_chat: "Общий чат", chat_rating_error: "Ваш рейтинг ниже 4 звезд. Доступ в чат закрыт.", chat_ph: "Напишите сообщение...", ad_placeholder: "Твоя реклама", hero_desc: "Безопасная биржа фриланса. Найдите идеального исполнителя для ваших задач.", 
    sort: "Сортировка", sort_new: "Сначала новые", sort_cheap: "Сначала дешевые", sort_exp: "Сначала дорогие", sort_top: "По рейтингу", 
    fav_only: "Мои закладки", show_hidden: "Скрытые", back_to_all: "Вернуться ко всем", hide_btn: "Скрыть", unhide_btn: "Вернуть", 
    buy_now: "Оплатить", title: "UNIT Marketplace — Цифровые Услуги", sub: "ОБЪЯВЛЕНИЯ", search: "Найти услуги или задания", 
    track_orders: "Мои Заказы", admin: "АДМИН", login: "Войти", logout: "Выйти", register: "Регистрация", pass_q: "Пароль", 
    auth_req: "Войдите в аккаунт, чтобы продолжить", no_acc: "Нет аккаунта?", has_acc: "Уже есть аккаунт?", msg: "Заказ принят!", 
    rub_cat: "Рубрики", rub_bud: "Фильтр по бюджету", cat_all: "Все категории", cat_design: "Дизайн", cat_dev: "Разработка и IT", 
    cat_text: "Тексты и переводы", cat_seo: "SEO и трафик", cat_social: "Соцсети и маркетинг", cat_audio: "Аудио, видео, съемка", 
    cat_bus: "Бизнес и жизнь", cat_photo: "Фотография", cat_anim: "Анимация и 3D", cat_edu: "Обучение и консалтинг", 
    regulations: "Регламент", rodo: "Политика конфиденциальности (RODO)", footer_rights: "Все права защищены.", no_orders: "Ничего не найдено", 
    profile: "Кабинет", show_all: "Показать всё", buyer: "Продавец", projects_on_exchange: "Проектов на бирже", hired_on: "Успешно сдано", 
    rest_time: "Срок: 1-3 дня", review_btn: "Смотреть", order: "Заказать", reviews_count: "Отзывов", delete: "Удалить", 
    btn_rate: "⭐ Оценить", modal_review_title: "Оставьте отзыв", ph_review: "Напишите пару слов о работе...", btn_send_review: "Отправить отзыв", 
    review_success: "Спасибо за ваш отзыв!", help_btn: "Помощь", help_title: "Справка и вопросы", help_q1: "Как сделать заказ?", 
    help_a1: "Авторизуйтесь, выберите нужную услугу из каталога и нажмите кнопку 'Заказать'. Ваш заказ появится в разделе 'Мои заказы'.", 
    help_q2: "Как работает рейтинг и отзывы?", help_a2: "После того как статус заказа изменится на 'Done' или 'Completed', у вас появится кнопка 'Оценить'. Оставленный отзыв напрямую влияет на рейтинг исполнителя.", 
    help_q3: "Для чего нужен Общий чат?", help_a3: "В Общем чате можно найти исполнителя, обсудить условия или предложить свои услуги. Он доступен пользователям с рейтингом от 4 звезд.", 
    modal_review_desc: "Оцените фрилансера по трем критериям:", modal_review_quality: "Качество работы", modal_review_punctuality: "Соблюдение сроков", modal_review_price: "Адекватность цены", 
    tasks: "Биржа заданий", services: "Каталог услуг", btn_apply: "Откликнуться", my_tasks: "Мои задания", create_task: "Создать задание", 
    menu: "Меню", language: "Язык", currency: "Валюта", from: "От", to: "До", no_active_tasks: "Нет активных заданий в этой категории", 
    reset_search: "Сбросить поиск", found: "Найдено:", view_grid: "Плиткой", view_list: "Списком", loading: "Загрузка...",
    top_badge: "ТОП", unit_seller: "Продавец", online: "В сети", pro: "Pro", top: "Top",
    logged_in_as: "Вы вошли как", notifications: "Уведомления", mark_all_read: "Прочитать все", no_new_notifications: "Нет новых уведомлений",
    apply_title: "Оставить отклик", apply_ph: "Опишите, почему вы справитесь с этим заданием и ваш опыт...", apply_submit: "Отправить отклик"
  },
  EN: { 
    global_chat: "Global Chat", chat_rating_error: "Your rating is below 4 stars. Chat access denied.", chat_ph: "Type a message...", ad_placeholder: "Your Ad Here", hero_desc: "Safe freelance marketplace. Find the perfect expert for your tasks.", 
    sort: "Sort by", sort_new: "Newest first", sort_cheap: "Cheapest first", sort_exp: "Most expensive", sort_top: "By Rating", 
    fav_only: "My Favorites", show_hidden: "Hidden", back_to_all: "Back to active", hide_btn: "Hide", unhide_btn: "Unhide", 
    buy_now: "Pay Now", title: "UNIT Marketplace — Digital Services", sub: "LISTINGS", search: "Search services or tasks", 
    track_orders: "My Orders", admin: "ADMIN", login: "Login", logout: "Logout", register: "Sign Up", pass_q: "Password", 
    auth_req: "Please login to continue", no_acc: "No account?", has_acc: "Already have an account?", msg: "Order accepted!", 
    rub_cat: "Categories", rub_bud: "Budget Filter", cat_all: "All categories", cat_design: "Design", cat_dev: "Development & IT", 
    cat_text: "Texts & Translation", cat_seo: "SEO & Traffic", cat_social: "Social Media", cat_audio: "Audio & Video", 
    cat_bus: "Business & Life", cat_photo: "Photography", cat_anim: "Animation & 3D", cat_edu: "Lessons & Consulting", 
    regulations: "Terms of Service", rodo: "Privacy Policy (GDPR)", footer_rights: "All rights reserved.", no_orders: "Nothing found", 
    profile: "Profile", show_all: "Show all", buyer: "Seller", projects_on_exchange: "Projects", hired_on: "Success rate", 
    rest_time: "Time: 1-3 days", review_btn: "View", order: "Order", reviews_count: "Reviews", delete: "Delete", 
    btn_rate: "⭐ Rate", modal_review_title: "Leave a review", ph_review: "Write a few words about the work...", btn_send_review: "Send review", 
    review_success: "Thank you for your review!", help_btn: "Help", help_title: "Help & FAQ", help_q1: "How to order?", 
    help_a1: "Log in, select a service and click 'Order'. Track it in 'My Orders'.", help_q2: "How do reviews work?", help_a2: "Once the order is 'Done', you can rate it. Reviews affect the seller's rating.", 
    help_q3: "What is Global Chat?", help_a3: "Use it to find experts or offer services. Available for users with 4+ stars.", 
    modal_review_desc: "Rate the freelancer on three criteria:", modal_review_quality: "Quality of work", modal_review_punctuality: "Punctuality", modal_review_price: "Fairness of price", 
    tasks: "Task Exchange", services: "Services Catalog", btn_apply: "Apply", my_tasks: "My Tasks", create_task: "Create Task", 
    menu: "Menu", language: "Language", currency: "Currency", from: "From", to: "To", no_active_tasks: "No active tasks in this category", 
    reset_search: "Reset search", found: "Found:", view_grid: "Grid", view_list: "List", loading: "Loading...",
    top_badge: "TOP", unit_seller: "Seller", online: "Online", pro: "Pro", top: "Top",
    logged_in_as: "Logged in as", notifications: "Notifications", mark_all_read: "Mark all as read", no_new_notifications: "No new notifications",
    apply_title: "Submit an application", apply_ph: "Describe why you are the best fit for this task...", apply_submit: "Send application"
  },
  PL: { 
    global_chat: "Czat Ogólny", chat_rating_error: "Twój ranking to poniżej 4 gwiazdek. Brak dostępu.", chat_ph: "Napisz wiadomość...", ad_placeholder: "Twoja Reklama", hero_desc: "Bezpieczna giełda freelance. Znajdź idealnego wykonawcę do swoich zadań.", 
    sort: "Sortuj", sort_new: "Od najnowszych", sort_cheap: "Od najtańszych", sort_exp: "Od najdroższych", sort_top: "Według oceny", 
    fav_only: "Moje ulubione", show_hidden: "Ukryte", back_to_all: "Wróć do aktywnych", hide_btn: "Ukryj", unhide_btn: "Przywróć", 
    buy_now: "Zapłać", title: "UNIT Marketplace — Usługi Cyfrowe", sub: "OGŁOSZENIA", search: "Szukaj usług lub zadań", 
    track_orders: "Moje Zamówienia", admin: "ADMIN", login: "Zaloguj się", logout: "Wyloguj", register: "Rejestracja", pass_q: "Hasło", 
    auth_req: "Zaloguj się, aby kontynuować", no_acc: "Brak konta?", has_acc: "Masz już konto?", msg: "Zamówienie przyjęte!", 
    rub_cat: "Kategorie", rub_bud: "Filtr budżetu", cat_all: "Wszystkie kategorie", cat_design: "Design", cat_dev: "Programowanie i IT", 
    cat_text: "Teksty i Tłumaczenia", cat_seo: "SEO i Ruch", cat_social: "Media Społecznościowe", cat_audio: "Audio i Wideo", 
    cat_bus: "Biznes i Życie", cat_photo: "Fotografia", cat_anim: "Animacja i 3D", cat_edu: "Szkolenia i Konsultacje", 
    regulations: "Regulamin", rodo: "Polityka prywatności (RODO)", footer_rights: "Wszelkie prawa zastrzeżone.", no_orders: "Nic nie znaleziono", 
    profile: "Profil", show_all: "Pokaż wszystko", buyer: "Sprzedawca", projects_on_exchange: "Projekty", hired_on: "Sukces", 
    rest_time: "Czas: 1-3 dni", review_btn: "Zobacz", order: "Zamów", reviews_count: "Opinie", delete: "Usuń", 
    btn_rate: "⭐ Oceń", modal_review_title: "Zostaw opinię", ph_review: "Napisz kilka słów o pracy...", btn_send_review: "Wyślij opinię", 
    review_success: "Dziękujemy za Twoją opinię!", help_btn: "Pomoc", help_title: "Pomoc i FAQ", help_q1: "Jak złożyć zamówienie?", 
    help_a1: "Zaloguj się, wybierz usługę i kliknij 'Zamów'.", help_q2: "Jak działają opinie?", help_a2: "Gdy zamówienie zostanie zakończone, będziesz mógł je ocenić.", 
    help_q3: "Do czego służy Czat?", help_a3: "Znajdź eksperta lub zaoferuj usługi. Dostępne od 4 gwiazdek.", 
    modal_review_desc: "Oceń freelancera według trzech kryteriów:", modal_review_quality: "Jakość pracy", modal_review_punctuality: "Punktualność", modal_review_price: "Uczciwość ceny", 
    tasks: "Giełda Zadań", services: "Katalog Usług", btn_apply: "Aplikuj", my_tasks: "Moje zadania", create_task: "Stwórz zadanie", 
    menu: "Menu", language: "Język", currency: "Waluta", from: "Od", to: "Do", no_active_tasks: "Brak aktywnych zadań w tej kategorii", 
    reset_search: "Zresetuj wyszukiwanie", found: "Znaleziono:", view_grid: "Siatka", view_list: "Lista", loading: "Ładowanie...",
    top_badge: "TOP", unit_seller: "Sprzedawca", online: "Online", pro: "Pro", top: "Top",
    logged_in_as: "Zalogowano jako", notifications: "Powiadomienia", mark_all_read: "Oznacz wszystkie jako przeczytane", no_new_notifications: "Brak nowych powiadomień",
    apply_title: "Złóż ofertę", apply_ph: "Opisz, dlaczego poradzisz sobie z tym zadaniem...", apply_submit: "Wyślij ofertę"
  },
  DE: { 
    global_chat: "Globaler Chat", chat_rating_error: "Ihre Bewertung liegt unter 4 Sternen. Zugriff verweigert.", chat_ph: "Nachricht schreiben...", ad_placeholder: "Deine Werbung", hero_desc: "Sicherer Freelance-Marktplatz. Finden Sie den perfekten Experten für Ihre Aufgaben.", 
    sort: "Sortieren", sort_new: "Neueste zuerst", sort_cheap: "Günstigste zuerst", sort_exp: "Teuerste zuerst", sort_top: "Nach Bewertung", 
    fav_only: "Meine Favoriten", show_hidden: "Ausgeblendet", back_to_all: "Zurück zu aktiven", hide_btn: "Ausblenden", unhide_btn: "Einblenden", 
    buy_now: "Bezahlen", title: "UNIT Marketplace — Digitale Dienste", sub: "ANZEIGEN", search: "Dienste oder Aufgaben suchen", 
    track_orders: "Meine Bestellungen", admin: "ADMIN", login: "Anmelden", logout: "Abmelden", register: "Registrieren", pass_q: "Passwort", 
    auth_req: "Bitte einloggen, um fortzufahren", no_acc: "Kein Konto?", has_acc: "Bereits ein Konto?", msg: "Bestellung angenommen!", 
    rub_cat: "Kategorien", rub_bud: "Budgetfilter", cat_all: "Alle Kategorien", cat_design: "Design", cat_dev: "Entwicklung & IT", 
    cat_text: "Texte & Übersetzungen", cat_seo: "SEO & Traffic", cat_social: "Soziale Medien", cat_audio: "Audio & Video", 
    cat_bus: "Business & Leben", cat_photo: "Fotografie", cat_anim: "Animation & 3D", cat_edu: "Schulung & Beratung", 
    regulations: "Nutzungsbedingungen", rodo: "Datenschutzerklärung (DSGVO)", footer_rights: "Alle Rechte vorbehalten.", no_orders: "Nichts gefunden", 
    profile: "Kabinett", show_all: "Alles anzeigen", buyer: "Verkäufer", projects_on_exchange: "Projekte", hired_on: "Erfolgsquote", 
    rest_time: "Zeit: 1-3 Tage", review_btn: "Ansehen", order: "Bestellen", reviews_count: "Bewertungen", delete: "Löschen", 
    btn_rate: "⭐ Bewerten", modal_review_title: "Bewertung hinterlassen", ph_review: "Schreibe ein paar Worte über die Arbeit...", btn_send_review: "Bewertung senden", 
    review_success: "Danke für deine Bewertung!", help_btn: "Hilfe", help_title: "Hilfe & FAQ", help_q1: "Wie bestelle ich?", 
    help_a1: "Einloggen, Service wählen und bestellen.", help_q2: "Wie funktionieren Bewertungen?", help_a2: "Nach Abschluss können Sie eine Bewertung abgeben.", 
    help_q3: "Was ist der Chat?", help_a3: "Für Nutzer ab 4 Sternen. Experten finden.", 
    modal_review_desc: "Bewerten Sie den Freelancer nach drei Kriterien:", modal_review_quality: "Qualität der Arbeit", modal_review_punctuality: "Pünktlichkeit", modal_review_price: "Preis-Leistungs-Verhältnis", 
    tasks: "Aufgabenbörse", services: "Dienstleistungen", btn_apply: "Bewerben", my_tasks: "Meine Aufgaben", create_task: "Aufgabe erstellen", 
    menu: "Menü", language: "Sprache", currency: "Währung", from: "Von", to: "Bis", no_active_tasks: "Keine Aufgaben in dieser Kategorie", 
    reset_search: "Suche zurücksetzen", found: "Gefunden:", view_grid: "Raster", view_list: "Liste", loading: "Laden...",
    top_badge: "TOP", unit_seller: "Verkäufer", online: "Online", pro: "Pro", top: "Top",
    logged_in_as: "Angemeldet als", notifications: "Benachrichtigungen", mark_all_read: "Alle als gelesen markieren", no_new_notifications: "Keine neuen Benachrichtigungen",
    apply_title: "Angebot senden", apply_ph: "Beschreibe, warum du für diese Aufgabe am besten geeignet bist...", apply_submit: "Angebot senden"
  },
  ES: { 
    global_chat: "Chat Global", chat_rating_error: "Tu calificación es menor a 4 estrellas. Acceso denegado.", chat_ph: "Escribe un mensaje...", ad_placeholder: "Tu Anuncio", hero_desc: "Mercado seguro de freelancers. Encuentra al experto ideal para tus tareas.", 
    sort: "Ordenar por", sort_new: "Más recientes", sort_cheap: "Más baratos", sort_exp: "Más caros", sort_top: "Por calificación", 
    fav_only: "Mis favoritos", show_hidden: "Ocultos", back_to_all: "Volver a activos", hide_btn: "Ocultar", unhide_btn: "Mostrar", 
    buy_now: "Pagar", title: "UNIT Marketplace — Servicios Digitales", sub: "ANUNCIOS", search: "Buscar servicios o tareas", 
    track_orders: "Mis Pedidos", admin: "ADMIN", login: "Iniciar sesión", logout: "Cerrar sesión", register: "Regístrate", pass_q: "Contraseña", 
    auth_req: "Inicie sesión para continuar", no_acc: "¿No tienes cuenta?", has_acc: "¿Ya tienes cuenta?", msg: "¡Pedido aceptado!", 
    rub_cat: "Categorías", rub_bud: "Filtro de presupuesto", cat_all: "Todas las categorías", cat_design: "Diseño", cat_dev: "Desarrollo y TI", 
    cat_text: "Textos y Traducción", cat_seo: "SEO y Tráfico", cat_social: "Redes Sociales", cat_audio: "Audio y Video", 
    cat_bus: "Negocios y Vida", cat_photo: "Fotografía", cat_anim: "Animación y 3D", cat_edu: "Clases y Consultoría", 
    regulations: "Términos de servicio", rodo: "Política de privacidad (RGPD)", footer_rights: "Todos los derechos reservados.", no_orders: "Nada encontrado", 
    profile: "Perfil", show_all: "Mostrar todo", buyer: "Vendedor", projects_on_exchange: "Proyectos", hired_on: "Éxito", 
    rest_time: "Tiempo: 1-3 días", review_btn: "Ver", order: "Pedir", reviews_count: "Reseñas", delete: "Eliminar", 
    btn_rate: "⭐ Calificar", modal_review_title: "Deja una reseña", ph_review: "Escribe algunas palabras sobre el trabajo...", btn_send_review: "Enviar reseña", 
    review_success: "¡Gracias por tu reseña!", help_btn: "Ayuda", help_title: "Ayuda y FAQ", help_q1: "¿Cómo pedir?", 
    help_a1: "Inicia sesión, elige un servicio y pídelo.", help_q2: "¿Cómo calificar?", help_a2: "Después de completar, podrás calificar.", 
    help_q3: "¿Qué es el Chat?", help_a3: "Para usuarios con 4+ estrellas.", 
    modal_review_desc: "Califica al freelancer en tres criterios:", modal_review_quality: "Calidad del trabajo", modal_review_punctuality: "Puntualidad", modal_review_price: "Precio justo", 
    tasks: "Bolsa de Tareas", services: "Catálogo de Servicios", btn_apply: "Aplicar", my_tasks: "Mis tareas", create_task: "Crear tarea", 
    menu: "Menú", language: "Idioma", currency: "Moneda", from: "Desde", to: "Hasta", no_active_tasks: "No hay tareas en esta categoría", 
    reset_search: "Restablecer búsqueda", found: "Encontrado:", view_grid: "Cuadrícula", view_list: "Lista", loading: "Cargando...",
    top_badge: "TOP", unit_seller: "Vendedor", online: "En línea", pro: "Pro", top: "Top",
    logged_in_as: "Conectado como", notifications: "Notificaciones", mark_all_read: "Marcar todo como leído", no_new_notifications: "No hay notificaciones nuevas",
    apply_title: "Enviar propuesta", apply_ph: "Describe por qué eres el mejor para esta tarea...", apply_submit: "Enviar propuesta"
  },
  IT: { 
    global_chat: "Chat Globale", chat_rating_error: "La tua valutazione è inferiore a 4 stelle. Accesso negato.", chat_ph: "Scrivi un messaggio...", ad_placeholder: "La Tua Pubblicità", hero_desc: "Mercato freelance sicuro. Trova l'esperto ideale per i tuoi compiti.", 
    sort: "Ordina per", sort_new: "Più recenti", sort_cheap: "Più economici", sort_exp: "Più costosi", sort_top: "Per valutazione", 
    fav_only: "I miei preferiti", show_hidden: "Nascosti", back_to_all: "Torna agli attivi", hide_btn: "Nascondi", unhide_btn: "Mostra", 
    buy_now: "Paga", title: "UNIT Marketplace — Servizi Digitali", sub: "ANNUNCI", search: "Cerca servizi o compiti", 
    track_orders: "I miei ordini", admin: "ADMIN", login: "Accedi", logout: "Esci", register: "Iscriviti", pass_q: "Password", 
    auth_req: "Accedi per continuare", no_acc: "Nessun account?", has_acc: "Hai già un account?", msg: "Ordine accettato!", 
    rub_cat: "Categorie", rub_bud: "Filtro budget", cat_all: "Tutte le categorie", cat_design: "Design", cat_dev: "Sviluppo e IT", 
    cat_text: "Testi e Traduzioni", cat_seo: "SEO e Traffico", cat_social: "Social Media", cat_audio: "Audio i Video", 
    cat_bus: "Affari e Vita", cat_photo: "Fotografia", cat_anim: "Animazione e 3D", cat_edu: "Formazione e Consulenza", 
    regulations: "Termini di servizio", rodo: "Informativa sulla privacy (GDPR)", footer_rights: "Tutti i diritti riservati.", no_orders: "Nessun risultato", 
    profile: "Profilo", show_all: "Mostra tutto", buyer: "Venditore", projects_on_exchange: "Progetti", hired_on: "Successo", 
    rest_time: "Tempo: 1-3 giorni", review_btn: "Visualizza", order: "Ordina", reviews_count: "Recensioni", delete: "Elimina", 
    btn_rate: "⭐ Valuta", modal_review_title: "Lascia una recensione", ph_review: "Scrivi qualche parola sul lavoro...", btn_send_review: "Invia recensione", 
    review_success: "Grazie per la tua recensione!", help_btn: "Aiuto", help_title: "Aiuto & FAQ", help_q1: "Come ordinare?", 
    help_a1: "Accedi e clicca 'Ordina'.", help_q2: "Come recensire?", help_a2: "Potrai recensire a lavoro finito.", 
    help_q3: "A cosa serve la Chat?", help_a3: "Trova esperti, disponibile da 4 stelle in su.", 
    modal_review_desc: "Valuta il freelancer su tre criteri:", modal_review_quality: "Qualità del lavoro", modal_review_punctuality: "Puntualità", modal_review_price: "Prezzo equo", 
    tasks: "Borsa del Lavoro", services: "Catalogo Servizi", btn_apply: "Candidati", my_tasks: "I miei compiti", create_task: "Crea compito", 
    menu: "Menu", language: "Lingua", currency: "Valuta", from: "Da", to: "A", no_active_tasks: "Nessun compito in questa categoria", 
    reset_search: "Reimposta ricerca", found: "Trovato:", view_grid: "Griglia", view_list: "Lista", loading: "Caricamento...",
    top_badge: "TOP", unit_seller: "Venditore", online: "Online", pro: "Pro", top: "Top",
    logged_in_as: "Connesso come", notifications: "Notifiche", mark_all_read: "Segna tutti come letti", no_new_notifications: "Nessuna nuova notifica",
    apply_title: "Invia proposta", apply_ph: "Descrivi perché sei il migliore per questo compito...", apply_submit: "Invia proposta"
  },
  FR: { 
    global_chat: "Chat Global", chat_rating_error: "Votre note est inférieure à 4 étoiles. Accès refusé.", chat_ph: "Écrivez un message...", ad_placeholder: "Votre Publicité", hero_desc: "Marché freelance sécurisé. Trouvez l'expert idéal pour vos tâches.", 
    sort: "Trier par", sort_new: "Plus récents", sort_cheap: "Moins chers", sort_exp: "Plus chers", sort_top: "Par note", 
    fav_only: "Mes favoris", show_hidden: "Masqués", back_to_all: "Retour aux actifs", hide_btn: "Masquer", unhide_btn: "Afficher", 
    buy_now: "Payer", title: "UNIT Marketplace — Services Numériques", sub: "ANNONCES", search: "Rechercher des services ou tâches", 
    track_orders: "Mes commandes", admin: "ADMIN", login: "Se connecter", logout: "Se déconnecter", register: "S'inscrire", pass_q: "Mot de passe", 
    auth_req: "Veuillez vous connecter", no_acc: "Pas de compte?", has_acc: "Déjà un compte?", msg: "Commande acceptée!", 
    rub_cat: "Catégories", rub_bud: "Filtre budget", cat_all: "Toutes catégories", cat_design: "Design", cat_dev: "Développement et informatique", 
    cat_text: "Textes et traduction", cat_seo: "SEO et trafic", cat_social: "Réseaux sociaux", cat_audio: "Audio et vidéo", 
    cat_bus: "Affaires et vie", cat_photo: "Photographie", cat_anim: "Animation & 3D", cat_edu: "Cours & Conseil", 
    regulations: "Conditions d'utilisation", rodo: "Politique de confidentialité (RGPD)", footer_rights: "Tous droits réservés.", no_orders: "Rien n'a été trouvé", 
    profile: "Profil", show_all: "Tout afficher", buyer: "Vendeur", projects_on_exchange: "Projets", hired_on: "Succès", 
    rest_time: "Temps: 1-3 jours", review_btn: "Voir", order: "Commander", reviews_count: "Avis", delete: "Supprimer", 
    btn_rate: "⭐ Évaluer", modal_review_title: "Laisser un avis", ph_review: "Écrivez quelques mots sur le travail...", btn_send_review: "Envoyer l'avis", 
    review_success: "Merci pour votre avis !", help_btn: "Aide", help_title: "Aide et FAQ", help_q1: "Comment commander?", 
    help_a1: "Connectez-vous, choisissez et commandez.", help_q2: "Comment évaluer?", help_a2: "Évaluez après avoir terminé.", 
    help_q3: "Le Chat Global?", help_a3: "Pour les utilisateurs 4+ étoiles.", 
    modal_review_desc: "Évaluez le freelance selon trois critères :", modal_review_quality: "Qualité du travail", modal_review_punctuality: "Ponctualité", modal_review_price: "Justesse du prix", 
    tasks: "Bourse aux Tâches", services: "Catalogue de Services", btn_apply: "Postuler", my_tasks: "Mes tâches", create_task: "Créer une tâche", 
    menu: "Menu", language: "Langue", currency: "Devise", from: "De", to: "À", no_active_tasks: "Aucune tâche dans cette catégorie", 
    reset_search: "Réinitialiser la recherche", found: "Trouvé:", view_grid: "Grille", view_list: "Liste", loading: "Chargement...",
    top_badge: "TOP", unit_seller: "Vendeur", online: "En ligne", pro: "Pro", top: "Top",
    logged_in_as: "Connecté en tant que", notifications: "Notifications", mark_all_read: "Tout marquer comme lu", no_new_notifications: "Aucune nouvelle notification",
    apply_title: "Envoyer une proposition", apply_ph: "Décrivez pourquoi vous êtes le meilleur pour cette tâche...", apply_submit: "Envoyer la proposition"
  }
};

export const categories = [
  { id: 'ALL', titleKey: 'cat_all', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" /></svg> },
  { id: 'DESIGN', titleKey: 'cat_design', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" /></svg> },
  { id: 'DEV', titleKey: 'cat_dev', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg> },
  { id: 'TEXT', titleKey: 'cat_text', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg> },
  { id: 'SEO', titleKey: 'cat_seo', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg> },
  { id: 'SOCIAL', titleKey: 'cat_social', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2-2v6a2 2 0 002 2h2v4l.586-.586z" /></svg> },
  { id: 'AUDIO', titleKey: 'cat_audio', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg> },
  { id: 'PHOTO', titleKey: 'cat_photo', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"/><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"/></svg> },
  { id: 'ANIMATION', titleKey: 'cat_anim', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-14v4m0 0v10m0-14l-8 4m8 4l-8-4m0 0v10l8 4"/></svg> },
  { id: 'EDUCATION', titleKey: 'cat_edu', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" /></svg> },
  { id: 'BUSINESS', titleKey: 'cat_bus', icon: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg> }
];